# Generated by Django 3.0.6 on 2020-05-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.CharField(help_text='character limit 100', max_length=100)),
                ('destination', models.CharField(help_text='character limit 100', max_length=100)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('Height', models.FloatField()),
                ('weight', models.FloatField()),
                ('delivery_type', models.CharField(choices=[('FD', 'Fast Delivery'), ('MD', 'Within 2 to 4 days'), ('LD', 'Within a Week')], max_length=50)),
                ('shipment_type', models.CharField(choices=[('R', 'Return'), ('F', 'Forward')], max_length=30)),
            ],
        ),
    ]
